on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*'
name: Create Release on Tag Push
jobs:
  get-Tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.vars.outputs.tag }}
    steps:
      - uses: actions/checkout@v2
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}

  test:
    needs: get-Tag
    runs-on: ubuntu-latest
    container:
      image: flanksource/build-tools:v0.13.6
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: make build
  binary:
    needs: get-Tag
    runs-on: ubuntu-latest
    env:
      VERSION: v${{ needs.get-Tag.outputs.tag }}
    container:
      image: flanksource/build-tools:v0.13.6
    steps:
      - uses: actions/checkout@v2
      - run: make release
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./.bin/*
          tag: v${{ needs.get-Tag.outputs.tag }}
          overwrite: true
          file_glob: true
  docker:
    needs: get-Tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: flanksource/karina
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          snapshot: true
          tags: "latest,${{ needs.get-Tag.outputs.tag  }}"

  docs:
    runs-on: ubuntu-latest
    container:
      image: flanksource/build-tools:v0.12.0
    steps:
      - uses: actions/checkout@v2
      - run: make build-api-docs build-docs deploy-docs
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
